#!/usr/bin/env bash
# Script that installs Nginx on web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
