#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/morgance permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
rep_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$rep_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
