#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/morgance permanent;/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
rep_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$rep_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
