#!/usr/bin/env bash
#Bash script that loops from 1 to 10


res=0

while [ $res -lt 10 ]
do
if [ $res -eq 3 ]
then
echo "bad luck"
elif [ $res -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((res++))
done
