#!/usr/bin/env bash
#script that displays numbers from 1 to 20

 res=0

while [ ! $res -gt 20 ]
do
echo "$res"
case $res in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
((res++))
done
