#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes

times=0

while [ $times -le 12 ]
do
echo "Hour: $times"
minutes=1
while [ $minutes -lt 60 ]
do
echo "$minutes"
((minutes++))
done
((times++))
done
